.eslintrc, test/wave-packerSpec.js
add warning message tests for wave-packerSpec to
increase line coverage to the minimum 5%
=> test: add tests

.travis.yml, karma.conf.js, package.json
=> chore(karma): run tests in Chrome

test/web-audio-playerSpec.js
Add tests to raise line coverage to above the minimum 5 percent.
=> test(web-audio-player): add tests

karma.conf.js, package.json
fix istanbul throwing an exception when trying to 
generate html reports by introducing isparta
resolve #26
=> fix: fix istanbul

administrative-sdk/connection.js, administrative-sdk/pronunciationAnalysis.js, administrative-sdk/speechRecording.js
Add static method to connection to log RPC errors and correct
references to that method.
=> feat: add RPC error logging

administrative-sdk/base64Utils.js, administrative-sdk/choiceRecognition.js, administrative-sdk/pronunciationAnalysis.js, administrative-sdk/speechRecording.js
Move a method to convert an array buffer to base64 to a separate
utility class.
=> feat: add base64utils

administrative-sdk/basicAuth.js, administrative-sdk/choiceChallenge.js, administrative-sdk/choiceRecognition.js, administrative-sdk/organisation.js, administrative-sdk/pronunciationAnalysis.js, administrative-sdk/pronunciationChallenge.js, administrative-sdk/speechChallenge.js, administrative-sdk/speechRecording.js, administrative-sdk/student.js, administrative-sdk/tenant.js, test/basicAuthSpec.js, test/choiceChallengeSpec.js, test/choiceRecognitionSpec.js, test/organisationSpec.js, test/pronunciationAnalysisSpec.js, test/pronunciationChallengeSpec.js, test/speechChallengeSpec.js, test/speechRecordingSpec.js, test/studentSpec.js
refactored connection from instance field
to a parameter in every relevant method
=> refactor: use connection as parameter

administrative-sdk/choiceChallenge.js, administrative-sdk/choiceRecognition.js, administrative-sdk/connection.js, administrative-sdk/organisation.js, administrative-sdk/pronunciationAnalysis.js, administrative-sdk/pronunciationChallenge.js, administrative-sdk/speechChallenge.js, administrative-sdk/student.js, audio-tools.js, test/choiceChallengeSpec.js, test/choiceRecognitionSpec.js, test/organisationSpec.js, test/pronunciationAnalysisSpec.js, test/pronunciationChallengeSpec.js, test/speechChallengeSpec.js, test/studentSpec.js, wave-packer.js
make methods that dont use instance variables static
=> refactor: make methods static

administrative-sdk/pronunciationAnalysis.js
Fixed incorrect static method call.
=> fix: fix static method call

administrative-sdk/pronunciationAnalysis.js
Fix incorrect method references.
=> fix: fix incorrect references

index.js
Fix exports to reference class names.
=> fix(index): fix exports

audio-sdk.js, test/web-audio-recorderSpec.js, web-audio-recorder.js
Add 100% coverage tests for web-audio-recorder
Resolve #37
=> test(web-audio-recorder): add tests

administrative-sdk/basicAuth.js, administrative-sdk/choiceChallenge.js, administrative-sdk/choiceRecognition.js, administrative-sdk/connection.js, administrative-sdk/organisation.js, administrative-sdk/pronunciationAnalysis.js, administrative-sdk/pronunciationChallenge.js, administrative-sdk/speechChallenge.js, administrative-sdk/speechRecording.js, administrative-sdk/student.js, administrative-sdk/tenant.js, audio-sdk.js, audio-tools.js, cordova-media-player.js, cordova-media-recorder.js, test/choiceChallengeSpec.js, test/choiceRecognitionSpec.js, test/connectionSpec.js, test/organisationSpec.js, test/pronunciationAnalysisSpec.js, test/pronunciationChallengeSpec.js, test/speechChallengeSpec.js, test/speechRecordingSpec.js, test/studentSpec.js, web-audio-player.js
Disable all unneeded eslint overrides and fix style issues.
Resolve #20
=> Disable eslint

administrative-sdk/connection.js, audio-sdk.js
Fix reflect bugs that were unchecked.
Fix #60
=> fix(connection): fix reflect

administrative-sdk/choice-challenge/choice-challenge-controller.js, administrative-sdk/choice-recognition/choice-recognition-controller.js, administrative-sdk/organisation/organisation-controller.js, administrative-sdk/pronunciation-analysis/pronunciation-analysis-controller.js, administrative-sdk/pronunciation-challenge/pronunciation-challenge-controller.js, administrative-sdk/speech-challenge/speech-challenge-controller.js, administrative-sdk/speech-recording/speech-recording-controller.js, administrative-sdk/student/student-controller.js, test/choice-challengeSpec.js, test/choice-recognitionSpec.js, test/organisationSpec.js, test/pronunciation-analysisSpec.js, test/pronunciation-challengeSpec.js, test/speech-challengeSpec.js, test/speech-recordingSpec.js, test/studentSpec.js
Change static methods to instance methods.
=> refactor: revert static methods

administrative-sdk/connection/connection-controller.js, test/connectionSpec.js
Add method to get an oauth2 token.
=> feat(connection): add oauth2 token get

administrative-sdk/connection/connection-controller.js
Fix oauth2 request to submit HTTP form data instead of JSON. The server does not expect JSON.
=> fix(oauth2): fix oauth2 request

administrative-sdk/choice-recognition/choice-recognition-controller.js, administrative-sdk/pronunciation-analysis/pronunciation-analysis-controller.js, administrative-sdk/speech-recording/speech-recording-controller.js
Add error throwing and rejecting in the streaming methods.
=> feat: add error throwing

administrative-sdk/choice-recognition/choice-recognition-controller.js, administrative-sdk/pronunciation-analysis/pronunciation-analysis-controller.js, administrative-sdk/speech-recording/speech-recording-controller.js
Return promise.reject instead of throwing.
=> revert throw in promise

administrative-sdk/connection/connection-controller.js, test/basic-authSpec.js, test/choice-challengeSpec.js, test/choice-recognitionSpec.js, test/connectionSpec.js, test/pronunciation-analysisSpec.js, test/pronunciation-challengeSpec.js, test/speech-challengeSpec.js, test/speech-recordingSpec.js, test/studentSpec.js, test/tenantSpec.js, test/word-chunkSpec.js
100% test coverage for administrative sdk.
=> 100% coverage admin

administrative-sdk/connection/connection-controller.js, audio-player.js, audio-recorder.js, package.json, test/connectionSpec.js
Use event emitter package instead of custom implementation.
Resolve #66
=> refactor(events): use event emitters

test/cordova-media-recorderSpec.js
=> tests(cordovamediarecorder): add tests

cordova-media-player.js, test/cordova-media-playerSpec.js
=> tests(cordovamediaplayer): add tests

test/cordova-media-recorderSpec.js
Spy on window.Media in the beforeEach so this doesn't leak over to
subsequent tests.
=> fix(cordovamediarecorderspec): use beforeEach

audio-player.js
Add method to fire event that was somehow missing.
=> fix(audioplayer): add fire event

tools.js
=> refactor(tools): remove extend

audio-tools.js, test/audio-toolsSpec.js
=> tests(audiotools): add tests

test/media-recorderSpec.js
=> tests(mediarecorder): add tests

test/toolsSpec.js
=> tests(tools): add tests

test/wave-packerSpec.js, wave-packer.js
=> test(wave-packer): add tests

administrative-sdk/connection/connection-controller.js, test/connectionSpec.js
Fix scope parameters to include organisation and student.
Fix request to not make authorization header.
=> fix(oauth2): fix request

administrative-sdk/connection/connection-controller.js, audio-player.js, audio-recorder.js
Rewrite 'this' method assignments to es6 methods.
Resolve #81
=> refactor: use es6 methods

administrative-sdk/connection/connection-controller.js, audio-recorder.js
Use default args on fireEvent methods.
=> refactor: use default args

administrative-sdk/pronunciation-analysis/pronunciation-analysis-controller.js, test/choice-recognitionSpec.js, test/pronunciation-analysisSpec.js, test/speech-recordingSpec.js
Fix a bug in pronunciationanalysis and add tests for that bug in other streaming specs.
=> Streaming tests

audio-player.js, test/audio-playerSpec.js
=> tests(audioplayer): add tests

administrative-sdk/pronunciation-analysis/pronunciation-analysis-controller.js, test/pronunciation-analysisSpec.js
Fix the alignment call not being returned as a promise.
=> Fix alignment promise return

administrative-sdk/choice-recognition/choice-recognition-controller.js, administrative-sdk/pronunciation-analysis/pronunciation-analysis-controller.js, administrative-sdk/speech-recording/speech-recording-controller.js, test/choice-recognitionSpec.js, test/pronunciation-analysisSpec.js, test/speech-recordingSpec.js
Change and add notifying behaviour in streaming.
=> Change notify

administrative-sdk/connection/connection-controller.js, administrative-sdk/pronunciation-analysis/pronunciation-analysis-controller.js, administrative-sdk/pronunciation-challenge/pronunciation-challenge-controller.js, test/basic-authSpec.js, test/choice-challengeSpec.js, test/choice-recognitionSpec.js, test/connectionSpec.js, test/organisationSpec.js, test/pronunciation-analysisSpec.js, test/pronunciation-challengeSpec.js, test/speech-challengeSpec.js, test/speech-recordingSpec.js, test/studentSpec.js, test/tenantSpec.js
Refactor pronounciation urls and oauth2 headers for current its-ws and its-gae.
Resolve #88 and resolve #87
=> Refactor for new backend

administrative-sdk/student/student.js, test/studentSpec.js
Check if birthyear is a number and not a string.
=> fix(student): check birthyear for number

.babelrc, audio-recorder.js, karma.conf.js, package.json, test/audio-recorderSpec.js
Add 100% coverage tests, rewireify and babel loose mode for audio-recorderSpec.js
Resolve #85, resolve #21
=> Audio recorder spec

audio-player.js, test/audio-playerSpec.js
Add method and support to bind a stopwatch to a mediaplayer.
So users don't have to mess around doing complicated stuff.
=> feat(mediaplayer): add stopwatch binding

audio-recorder.js, cordova-media-player.js, test/cordova-media-playerSpec.js
Remove unused callback methods.
Probably resolves #22
=> refactor: remove unused callbacks

test/toolsSpec.js, tools.js
Tick and update the stopwatch one last time when stopping so the last
time update can be heard.
=> fix(stopwatch): tick when stopping

administrative-sdk/pronunciation-analysis/pronunciation-analysis-controller.js, test/audio-playerSpec.js, test/audio-recorderSpec.js, test/cordova-media-playerSpec.js, test/pronunciation-analysisSpec.js
Add missing tests for files that were modified and lost their 100% coverage.
=> Add missing tests

audio-recorder.js, test/audio-recorderSpec.js
Add stopwatch binding support for audiorecorder.
=> feat(audiorecorder): add stopwatch binding

audio-player.js, test/audio-playerSpec.js, test/web-audio-playerSpec.js, web-audio-player.js
Correct scrubbing errors instead of throwing errors and correct timer errors when it counts too high.
=> Correct errors

audio-recorder.js, test/audio-recorderSpec.js
Stop the recorder before stopping the timer.
=> fix(audiorecorder): stop recorder before timer

test/toolsSpec.js, tools.js
Check if tickCb exists and throw an error if it does not.
=> Tick cb error

administrative-sdk/connection/connection-controller.js, test/connectionSpec.js
Set the token in settings when getting it instead of leaving it to the
user.
=> feat(connection): set token when getting

administrative-sdk/basic-auth/basic-auth-controller.js, administrative-sdk/choice-challenge/choice-challenge-controller.js, administrative-sdk/choice-recognition/choice-recognition-controller.js, administrative-sdk/connection/connection-controller.js, administrative-sdk/organisation/organisation-controller.js, administrative-sdk/pronunciation-analysis/pronunciation-analysis-controller.js, administrative-sdk/pronunciation-challenge/pronunciation-challenge-controller.js, administrative-sdk/speech-challenge/speech-challenge-controller.js, administrative-sdk/speech-recording/speech-recording-controller.js, administrative-sdk/student/student-controller.js, administrative-sdk/tenant/tenant-controller.js, audio-player.js, audio-recorder.js, test/audio-playerSpec.js, test/audio-recorderSpec.js, test/pronunciation-analysisSpec.js
Prefix underscores to several variables so the documentation doesn't show it and people don't have to worry about seeing random variables they won't use directly.
=> Private variables

administrative-sdk/pronunciation-analysis/pronunciation-analysis-controller.js
Make the referencealignment member private.
=> refactor(pronunciationanalysis): make referencealignment private

test/toolsSpec.js, tools.js
Add methods for other entities to observe the ticking updates in case
someone is interested in seeing them.
=> feat(stopwatch): add observer functionality

administrative-sdk/organisation/organisation.js, administrative-sdk/pronunciation-challenge/pronunciation-challenge-controller.js, administrative-sdk/pronunciation-challenge/pronunciation-challenge.js, administrative-sdk/speech-challenge/speech-challenge-controller.js, administrative-sdk/student/student-controller.js, administrative-sdk/student/student.js, test/organisationSpec.js, test/pronunciation-analysisSpec.js, test/pronunciation-challengeSpec.js, test/speech-challengeSpec.js, test/studentSpec.js
Add checks for constructor parameter when they are or aren't required and how they are set on construction in requests.
=> Constructor error checking

administrative-sdk/connection/connection-controller.js
Use one method to handle request responses and repeat less code.
=> refactor(connection): use common method to handle response

package.json
=> fix: fix build

administrative-sdk/choice-recognition/choice-recognition-controller.js, administrative-sdk/pronunciation-analysis/pronunciation-analysis-controller.js, administrative-sdk/speech-recording/speech-recording-controller.js, test/choice-recognitionSpec.js, test/pronunciation-analysisSpec.js, test/speech-recordingSpec.js
Fix streaming ids set to null and fix tests that broke.
=> Fix id to null

audio-player.js, audio-recorder.js, audio-tools.js, cordova-media-player.js, cordova-media-recorder.js, media-recorder.js, tools.js, wave-packer.js, web-audio-player.js, web-audio-recorder.js
Add audio related documentation.
=> docs(audio): add audio related docs

audio-player.js, test/audio-playerSpec.js
Fix audioplayer to reset when loading audio.
=> fix(audioplayer): fix reset

administrative-sdk/choice-challenge/choice-challenge-controller.js, administrative-sdk/choice-recognition/choice-recognition-controller.js, test/choice-challengeSpec.js, test/choice-recognitionSpec.js
Remove organisation from url to match latest its-gae version.
=> fix(choice): remove organisation from url

administrative-sdk/pronunciation-challenge/pronunciation-challenge-controller.js, administrative-sdk/speech-challenge/speech-challenge-controller.js, administrative-sdk/speech-recording/speech-recording-controller.js, test/pronunciation-challengeSpec.js, test/speech-challengeSpec.js, test/speech-recordingSpec.js
Remove organization URL from speech and add a organisation id parameter to list pronunciation challenges.
=> Remove organisation remnants

administrative-sdk/connection/connection-controller.js, test/choice-challengeSpec.js, test/choice-recognitionSpec.js, test/connectionSpec.js, test/organisationSpec.js, test/pronunciation-analysisSpec.js, test/pronunciation-challengeSpec.js, test/speech-challengeSpec.js, test/speech-recordingSpec.js, test/studentSpec.js
Check header if the response body is JSON before handling it further.
=> fix(connection): check header

administrative-sdk/choice-challenge/choice-challenge-controller.js, administrative-sdk/choice-recognition/choice-recognition-controller.js, administrative-sdk/organisation/organisation-controller.js, administrative-sdk/pronunciation-analysis/pronunciation-analysis-controller.js, administrative-sdk/pronunciation-challenge/pronunciation-challenge-controller.js, administrative-sdk/speech-challenge/speech-challenge-controller.js, administrative-sdk/speech-recording/speech-recording-controller.js, administrative-sdk/student/student-controller.js, test/choice-challengeSpec.js, test/choice-recognitionSpec.js, test/organisationSpec.js, test/pronunciation-analysisSpec.js, test/pronunciation-challengeSpec.js, test/speech-challengeSpec.js, test/speech-recordingSpec.js, test/studentSpec.js
Add checks for parameters for some methods in choice, speech, pronunciation, student and organisation. Similar methods only checked some of the parameters or none at all which was inconsistent.
=> Add parameter checks

karma.conf.js, src/audio/audio-recorder.js, test/audio-recorderSpec.js, test/pronunciation-challengeSpec.js, test/studentSpec.js
Enforce 100% coverage and add tests
=> Full tests

index.js, src/administrative-sdk/administrative-sdk.js, test/administrative-sdkSpec.js
Add class that exposes all controller methods so users don't need to
create controller objects themselves.
=> feat(adminsdk): add facade class

src/administrative-sdk/administrative-sdk.js, src/administrative-sdk/choice-challenge/choice-challenge-controller.js, src/administrative-sdk/choice-recognition/choice-recognition-controller.js, src/administrative-sdk/connection/connection-controller.js, src/administrative-sdk/organisation/organisation-controller.js, src/administrative-sdk/pronunciation-analysis/pronunciation-analysis-controller.js, src/administrative-sdk/pronunciation-challenge/pronunciation-challenge-controller.js, src/administrative-sdk/speech-challenge/speech-challenge-controller.js, src/administrative-sdk/speech-recording/speech-recording-controller.js, src/administrative-sdk/student/student-controller.js, src/audio/audio-player.js, src/audio/audio-recorder.js, src/audio/cordova-media-player.js, src/audio/wave-packer.js, src/audio/web-audio-player.js, src/audio/web-audio-recorder.js, src/tools.js, test/audio-playerSpec.js, test/audio-recorderSpec.js, test/connectionSpec.js, test/cordova-media-playerSpec.js, test/toolsSpec.js, test/web-audio-playerSpec.js, test/web-audio-recorderSpec.js
Make some variables private so they don't show up in docs.
=> refactor: make variables private

karma.conf.js
Fix index reference to point to src folder first.
=> fix(karma): fix index reference

.travis.yml, deploy.sh
Fix travis cleaning up build artifacts that were needed.
Fix deploy.sh skipping build when releasing.
=> fix(deploy): fix deploy scripts

.gitignore
Add esdoc folder to gitignore.
=> chore(gitignore): add esdoc

.travis.yml, deploy.sh
Use file glob option to deploy whatever is inside the build folder.
=> chore(travis): use file glob

deploy.sh
Checkout master branch before running commands.
=> fix(deploy): checkout master

.travis.yml, deploy.sh
Run babelify before each deploy.
=> chore(travis):run babelify before deploy

.gitignore, deploy.sh
Run babelify in deploy sh and remove esdoc ignore.
=> Fix deploy

.travis.yml
Remove before deploy command as it is now done in the deploy.sh script.
=> chore(travis): remove before deploy command

.gitignore
Remove build folder from gitignore because travis needs it.
=> chore(gitignore): remove build

.gitignore
Reverts itslanguage/itslanguage-js#176
=> Revert "chore(gitignore): remove build"

src/administrative-sdk/choice-recognition/choice-recognition-controller.js, src/administrative-sdk/choice-recognition/choice-recognition.js, src/administrative-sdk/pronunciation-analysis/pronunciation-analysis-controller.js, src/administrative-sdk/pronunciation-analysis/pronunciation-analysis.js, src/administrative-sdk/speech-recording/speech-recording-controller.js, src/administrative-sdk/speech-recording/speech-recording.js, test/choice-recognitionSpec.js, test/pronunciation-analysisSpec.js, test/speech-recordingSpec.js
Add the dates and specific challenge result information to the constructor instead of setting it after construction.
=> Clean constructors

src/administrative-sdk/choice-recognition/choice-recognition-controller.js, src/administrative-sdk/pronunciation-analysis/pronunciation-analysis-controller.js, src/administrative-sdk/speech-recording/speech-recording-controller.js
Remove organisation id from WAMP calls.
=> refactor(streaming): remove organisation id

src/administrative-sdk/choice-recognition/choice-recognition-controller.js, src/administrative-sdk/pronunciation-analysis/pronunciation-analysis-controller.js, src/administrative-sdk/speech-recording/speech-recording-controller.js, test/choice-recognitionSpec.js, test/pronunciation-analysisSpec.js, test/speech-recordingSpec.js
Remove student dependencies as the calls should not return a student
object but just an id.
=> refactor(streaming): remove student deps

src/administrative-sdk/choice-recognition/choice-recognition.js, src/administrative-sdk/pronunciation-analysis/pronunciation-analysis.js, src/administrative-sdk/speech-recording/speech-recording-controller.js, src/administrative-sdk/speech-recording/speech-recording.js, test/choice-recognitionSpec.js, test/pronunciation-analysisSpec.js, test/speech-recordingSpec.js
Clarify the student and challenge parameters in some methods to `studentId` and `challengeId`.
=> Clarify vars

src/administrative-sdk/administrative-sdk.js, src/administrative-sdk/choice-challenge/choice-challenge-controller.js, src/administrative-sdk/choice-challenge/choice-challenge.js, src/administrative-sdk/choice-recognition/choice-recognition-controller.js, src/administrative-sdk/pronunciation-analysis/pronunciation-analysis-controller.js, src/administrative-sdk/pronunciation-challenge/pronunciation-challenge-controller.js, src/administrative-sdk/pronunciation-challenge/pronunciation-challenge.js, src/administrative-sdk/speech-challenge/speech-challenge-controller.js, src/administrative-sdk/speech-challenge/speech-challenge.js, src/administrative-sdk/speech-recording/speech-recording-controller.js, test/administrative-sdkSpec.js, test/choice-challengeSpec.js, test/choice-recognitionSpec.js, test/pronunciation-analysisSpec.js, test/pronunciation-challengeSpec.js, test/speech-challengeSpec.js, test/speech-recordingSpec.js
Remove organisation ID from choice, pronunciation and speech.
=> Remove organisation wamp

package.json, src/audio/audio-recorder.js, test/audio-recorderSpec.js
=> chore(package): replace guid

src/administrative-sdk/basic-auth/basic-auth.js, src/administrative-sdk/choice-challenge/choice-challenge.js, src/administrative-sdk/organisation/organisation.js, src/administrative-sdk/pronunciation-analysis/pronunciation-analysis-controller.js, src/administrative-sdk/pronunciation-challenge/pronunciation-challenge.js, src/administrative-sdk/speech-challenge/speech-challenge.js, src/administrative-sdk/student/student.js, src/audio/audio-player.js, src/audio/audio-recorder.js, src/audio/audio-tools.js, src/audio/cordova-media-player.js, src/audio/web-audio-player.js, src/audio/web-audio-recorder.js
The parameters that are nullable shouldn't be written in square brackets
but the type should be prefixed with a question mark.
Square brackets indicates an optional parameter meaning undefined is
allowed but that shouldn't be.
=> docs: make parameters nullable

src/administrative-sdk/choice-recognition/choice-recognition-controller.js, src/administrative-sdk/pronunciation-analysis/pronunciation-analysis-controller.js, src/administrative-sdk/speech-recording/speech-recording-controller.js
Remove duplicate and useless catches.
=> refactor(streaming): improve error handling

deploy.sh, package.json
Clear build folder before doing another build.
=> chore(deploy): clear build folder

test/basic-authSpec.js, test/choice-challengeSpec.js, test/choice-recognitionSpec.js, test/connectionSpec.js, test/organisationSpec.js, test/pronunciation-analysisSpec.js, test/pronunciation-challengeSpec.js, test/speech-challengeSpec.js, test/speech-recordingSpec.js, test/studentSpec.js
Remove jasmine ajax in the admin sdk tests. We don't use that anymore.
=> fix(tests): remove jasmine ajax

test/choice-recognitionSpec.js, test/pronunciation-analysisSpec.js, test/speech-recordingSpec.js
Fix challenge type made in some tests.
Fix organisationId reference from challenges.
=> Fix challenge tests

src/administrative-sdk/role/role.js, src/index.js, test/roleSpec.js
=> feat: add role

src/administrative-sdk/group/group.js, src/index.js, test/groupSpec.js
=> feat: add group

src/administrative-sdk/profile/profile.js, src/index.js, test/profileSpec.js
Add a profile model. A profile contains information about
a User like his name and date of birth.
=> feat(profile): add profile

src/administrative-sdk/administrative-sdk.js, src/administrative-sdk/email-credentials/email-credentials-controller.js, src/administrative-sdk/email-credentials/email-credentials.js, src/index.js, test/administrative-sdkSpec.js, test/email-credentialsSpec.js
Add emailCredentials model and controller.
Close #206
=> feat: add emailcreds

src/administrative-sdk/administrative-sdk.js, src/administrative-sdk/choice-recognition/choice-recognition-controller.js, src/administrative-sdk/choice-recognition/choice-recognition.js, src/administrative-sdk/connection/connection-controller.js, src/administrative-sdk/pronunciation-analysis/pronunciation-analysis-controller.js, src/administrative-sdk/pronunciation-analysis/pronunciation-analysis.js, src/administrative-sdk/speech-recording/speech-recording-controller.js, src/administrative-sdk/speech-recording/speech-recording.js, src/administrative-sdk/user/user-controller.js, src/administrative-sdk/user/user.js, src/index.js, test/administrative-sdkSpec.js, test/choice-recognitionSpec.js, test/connectionSpec.js, test/pronunciation-analysisSpec.js, test/speech-recordingSpec.js, test/userSpec.js
Refactor student to user.
Close #178
=> refactor: student to user

src/administrative-sdk/choice-challenge/choice-challenge-controller.js, src/administrative-sdk/pronunciation-challenge/pronunciation-challenge-controller.js, src/administrative-sdk/speech-challenge/speech-challenge-controller.js, test/choice-challengeSpec.js, test/pronunciation-challengeSpec.js, test/speech-challengeSpec.js
You can just stringify the object and submit it. No need to do some
manual FormData stuff.
=> refactor(challenges): remove manual formdata

src/administrative-sdk/basic-auth/basic-auth.js, test/basic-authSpec.js
Change parameters for basicauth to forbid undefineds.
=> No undefined basic auth

package.json
Time I took official credit :)
=> chore(package): specify me as contributor

src/administrative-sdk/connection/connection-controller.js, test/connectionSpec.js
Add disconnect method and change specs to make them individually runnable.
=> Add disconnect

src/administrative-sdk/administrative-sdk.js, src/administrative-sdk/choice-challenge/choice-challenge-controller.js, src/administrative-sdk/choice-recognition/choice-recognition-controller.js, src/administrative-sdk/connection/connection-controller.js, src/administrative-sdk/email-credentials/email-credentials-controller.js, src/administrative-sdk/organisation/organisation-controller.js, src/administrative-sdk/pronunciation-analysis/pronunciation-analysis-controller.js, src/administrative-sdk/pronunciation-challenge/pronunciation-challenge-controller.js, src/administrative-sdk/speech-challenge/speech-challenge-controller.js, src/administrative-sdk/speech-recording/speech-recording-controller.js, src/administrative-sdk/user/user-controller.js
Improve documentation for method params and throws.
=> Improve docs

src/index.js
Remove some exports that should not be exported.
=> refactor(index): remove some exports

src/administrative-sdk/connection/connection-controller.js, test/connectionSpec.js
Get authentication with user credentials.
Closes #223
=> feat(connection): get user auth

src/administrative-sdk/administrative-sdk.js, src/administrative-sdk/role/role-controller.js, test/administrative-sdkSpec.js, test/roleSpec.js
Add role controller and method to list roles.
=> feat(roles): can list roles

src/administrative-sdk/administrative-sdk.js, src/administrative-sdk/email-credentials/email-credentials-controller.js, src/administrative-sdk/email-credentials/email-credentials.js, test/email-credentialsSpec.js
Changes to the EmailCredentials model and controller.
Documentation is updated, and password is now an optional parameter with default value.
=> Update email creds ctrl

src/administrative-sdk/category/category.js, src/administrative-sdk/progress/progress.js, src/index.js, test/categorySpec.js
Add category and progress model.
=> feat: add progress and category

src/administrative-sdk/administrative-sdk.js, src/administrative-sdk/role/role-controller.js, test/administrative-sdkSpec.js, test/roleSpec.js
Add method to get one role. Update docs for listRoles().
Fixes #181
=> Add get role

src/administrative-sdk/speech-challenge/speech-challenge-controller.js, src/administrative-sdk/speech-challenge/speech-challenge.js, test/speech-challengeSpec.js
Add srt and image file parameters to the speechchallenge constructor.
Add srt and image file options when creating a speechchallenge.
Fixes #229
=> feat(speechchallenge): add srt and image file parameters

src/administrative-sdk/administrative-sdk.js, src/administrative-sdk/profile/profile-controller.js, src/administrative-sdk/profile/profile.js, test/administrative-sdkSpec.js, test/profileSpec.js
Add profile controller and methods to get and list profiles.
Fixes #230
=> Profile controller

src/administrative-sdk/administrative-sdk.js, src/administrative-sdk/choice-challenge/choice-challenge-controller.js, src/administrative-sdk/choice-recognition/choice-recognition-controller.js, src/administrative-sdk/organisation/organisation-controller.js, src/administrative-sdk/profile/profile-controller.js, src/administrative-sdk/pronunciation-analysis/pronunciation-analysis-controller.js, src/administrative-sdk/pronunciation-challenge/pronunciation-challenge-controller.js, src/administrative-sdk/role/role-controller.js, src/administrative-sdk/speech-challenge/speech-challenge-controller.js, src/administrative-sdk/speech-recording/speech-recording-controller.js, src/administrative-sdk/user/user-controller.js, test/administrative-sdkSpec.js, test/choice-challengeSpec.js, test/choice-recognitionSpec.js, test/organisationSpec.js, test/profileSpec.js, test/pronunciation-analysisSpec.js, test/pronunciation-challengeSpec.js, test/roleSpec.js, test/speech-challengeSpec.js, test/speech-recordingSpec.js, test/userSpec.js
Rename methods like listUsers to getUsers. This is more in line with the
method names for getting a single object.
To get one user: getUser.
To get multiple users: getUsers.
Fixes #232
=> Rename listX to getX

test/choice-challengeSpec.js, test/organisationSpec.js, test/pronunciation-challengeSpec.js, test/speech-challengeSpec.js
Remove error handling tests since that is already tested in connectionSpec.js
=> Remove error handling tests

src/administrative-sdk/administrative-sdk.js, src/administrative-sdk/organisation/organisation-controller.js, src/administrative-sdk/organisation/organisation.js, src/administrative-sdk/speech-challenge/speech-challenge-controller.js, src/administrative-sdk/speech-challenge/speech-challenge.js, test/organisationSpec.js, test/speech-challengeSpec.js, test/speech-recordingSpec.js
Improve constructor and controller parameter checking.
Check for nulls and types of parameters better.
=> Better parameter checking

src/administrative-sdk/basic-auth/basic-auth.js, src/administrative-sdk/category/category.js, src/administrative-sdk/choice-challenge/choice-challenge-controller.js, src/administrative-sdk/choice-challenge/choice-challenge.js, src/administrative-sdk/choice-recognition/choice-recognition-controller.js, src/administrative-sdk/email-credentials/email-credentials-controller.js, src/administrative-sdk/group/group.js, src/administrative-sdk/organisation/organisation-controller.js, src/administrative-sdk/organisation/organisation.js, src/administrative-sdk/profile/profile.js, src/administrative-sdk/pronunciation-analysis/pronunciation-analysis-controller.js, src/administrative-sdk/pronunciation-challenge/pronunciation-challenge.js, src/administrative-sdk/role/role.js, src/administrative-sdk/speech-challenge/speech-challenge.js, test/choice-challengeSpec.js, test/choice-recognitionSpec.js, test/email-credentialsSpec.js, test/organisationSpec.js, test/pronunciation-analysisSpec.js, test/pronunciation-challengeSpec.js, test/roleSpec.js
Big update to enforce every class to adhere to consistent styles:
All parameters will be checked first before anything is set in the classes.
All parameter checks are now properly done with a typecheck.
All optional parameters are now default to null.
Testing parameters is done via parameterization.
Error messages are in the style of 'X parameter of type "Y" is required.'
Update documentation to reflect these changes.
=> Consistency

CONTRIBUTING.md
Add workaround instructions to releasing a new itslanguage version to NPM.
=> docs(contributing): add instructions for release

src/administrative-sdk/administrative-sdk.js, src/administrative-sdk/category/category-controller.js, src/administrative-sdk/category/category.js, test/administrative-sdkSpec.js, test/categorySpec.js
Refactor category to new spec.
Add category controller and methods. Add to facade.
=> Category controller

src/administrative-sdk/choice-recognition/choice-recognition-controller.js, src/administrative-sdk/connection/connection-controller.js, src/administrative-sdk/pronunciation-analysis/pronunciation-analysis-controller.js, src/administrative-sdk/speech-recording/speech-recording-controller.js, test/connectionSpec.js
This call method delegates the call to the internal session and adds a
common prefix to all calls.
=> refactor: add public call method to connection

src/administrative-sdk/category/category-controller.js, src/administrative-sdk/choice-challenge/choice-challenge-controller.js, src/administrative-sdk/choice-recognition/choice-recognition-controller.js, src/administrative-sdk/organisation/organisation-controller.js, src/administrative-sdk/profile/profile-controller.js, src/administrative-sdk/pronunciation-analysis/pronunciation-analysis-controller.js, src/administrative-sdk/pronunciation-challenge/pronunciation-challenge-controller.js, src/administrative-sdk/role/role-controller.js, src/administrative-sdk/speech-challenge/speech-challenge-controller.js, src/administrative-sdk/speech-recording/speech-recording-controller.js, src/administrative-sdk/user/user-controller.js
The combination of forEach / push to new array is really ugly and
probably inefficient.
=> style: use Array map when appropriate

package.json, src/administrative-sdk/choice-recognition/choice-recognition-controller.js, src/administrative-sdk/pronunciation-analysis/pronunciation-analysis-controller.js, src/administrative-sdk/speech-recording/speech-recording-controller.js, src/administrative-sdk/utils/base64-utils.js
Reverts itslanguage/itslanguage-js#255
Apparently it simply breaks the recordings.
=> Revert "refactor: replace base64-utils with base64-js"

src/administrative-sdk/choice-recognition/choice-recognition-controller.js, src/administrative-sdk/pronunciation-analysis/pronunciation-analysis-controller.js, src/audio/wave-packer.js
This library outputs a log of logging, of which the logs when recording
are by far the most spammy.
These particular logging calls were removed.
=> refactor: remove recording logs

karma.conf.js, src/administrative-sdk/administrative-sdk.js, src/administrative-sdk/progress/progress-controller.js, src/administrative-sdk/progress/progress.js, src/index.js, test/administrative-sdkSpec.js, test/progressSpec.js
The test for the controller are not complete yet. If approved, I'll create an issue to address this.
=> feat(progress): add Progress and ProgressController

src/administrative-sdk/user/user-controller.js, src/administrative-sdk/user/user.js, test/userSpec.js
Profile has not been implemented on the API yet. Thus it should be at
least optional.
=> fix(User): Profile for User is now optional

src/administrative-sdk/administrative-sdk.js, src/administrative-sdk/progress/progress-controller.js, test/administrative-sdkSpec.js, test/progressSpec.js
Make it possible to provide roles as a filter so that the result will be
filtered (based on the roles passed).
=> feat(Progress): add role filter

src/administrative-sdk/pronunciation-analysis/pronunciation-analysis-controller.js, test/pronunciation-analysisSpec.js
=> fix(issue283): reject empty response better

README.md, karma.conf.js, package-lock.json, src/administrative-sdk/connection/connection-controller.js, src/api/auth.js, src/api/auth.spec.js, src/api/communication.js, src/api/communication.spec.js, test/connectionSpec.js
Refactor and extend the communication mechanism with the API to be more
dynamic/flexible. This makes it also to doe (authorised) PUT requets.
Also convert the authentication mechanism to functions using the new
communication mechanism.
Update the README.md to contain required information. It is still
incomplete; the rest will follow during the refactor.
=> refactor: begin the transition from classes to functions.

src/api/categories.js, src/api/categories.spec.js, src/api/challenges/choice.js, src/api/challenges/choice.spec.js, src/api/challenges/pronunciation.js, src/api/challenges/pronunciation.spec.js, src/api/challenges/speech.js, src/api/challenges/speech.spec.js, src/api/groups.js, src/api/groups.spec.js, src/api/organisations.js, src/api/organisations.spec.js, src/api/roles.js, src/api/roles.spec.js, src/api/users.js, src/api/users.spec.js
Refactor all simple CRUD APIs first. These are all very similar to one
another.
=> Refactor most REST APIs

.travis.yml
It seems not possible to add two "on:" elements for the script provider.
For this, we will add two script providers that run on different
triggers.
=> update script provider

packages/itslanguage/package.json, src/api/communication/index.js, src/api/communication/index.spec.js, src/api/communication/websocket.js, test/speech-challengeSpec.js
=> Fix allow itslanguage urls

.travis.yml, karma.conf.js
Make use of Chrome it's possibility to run tests on a headless chrome instance. Since we don't require any GUI testing this should be fine to do.
=> Run tests headless

src/api/challenges/feedback/speech.js, src/api/utils/audio-over-socket.js
=> feat: introduce feedback api in the SDK

CHANGELOG.md, src/WebAudio/Player.js
- Add pause functionality to the player
- Improve some esdoc
- Remove async/await from the load function
- Added some helper functions
=> Improve webaudio player

src/api/challenges/feedback/speech.js, src/audio/audio-recorder.js
- Add support for pause/resume to the SDK.
- Added a little "hack" to give back the current feedbackId on each feedback result.
- The recorder should be able to get a pause signal.
=> Feat feedback pause resume

CHANGELOG.md, src/WebAudio/Player.js
- Added GainNode to be able to control player volume.
- Some small fixes for pause/resume
- Some helper functions for advanced usage
- Changelog update
=> Webaudio player improvements

CHANGELOG.md, packages/itslanguage/package.json
=> Prepare v3.1.1 release

CHANGELOG.md, packages/itslanguage/package.json, src/audio/audio-recorder.js, src/audio/web-audio-recorder.js, test/audio-recorderSpec.js
Baseline about what happened: make it possible to stop the recorder from a paused state.
=> Improve pause modus

package.json, packages/itslanguage/package.json, src/api/challenges/feedback/index.js, src/api/challenges/feedback/index.spec.js
To be able to the use the Speech Feedback REST API, some functions where added.
=> Add feedback api functions

CHANGELOG.md, packages/api/CHANGELOG.md, packages/api/challenges/speech/recordings.js, packages/api/challenges/speech/recordings.spec.js, packages/api/package.json
=> Expose the create of the speech recording api

CHANGELOG.md, packages/api/CHANGELOG.md, packages/player/CHANGELOG.md, packages/recorder/CHANGELOG.md
Make them all point to the root CHANGELOG.md file.
This way we only need to update one changelog file.
=> Update the changelog files

CHANGELOG.md, babel.config.js, karma.conf.js, packages/recorder/README.md, packages/recorder/index.js, packages/recorder/index.spec.js, packages/recorder/plugins/amplitude/amplitude.js, packages/recorder/plugins/amplitude/amplitude.spec.js, packages/recorder/plugins/amplitude/index.js, packages/recorder/plugins/amplitude/index.spec.js
- Made it possible to load plugins.
- Added the Amplitude plugin.
Refs #335
=> Enhance recorder

CHANGELOG.md, package.json, packages/api/README.md, packages/api/index.js, packages/api/package.json, packages/player/package.json, packages/recorder/package.json
- Prepped v4.2.0
- Prettier ran over the files changed
=> Prepare v4.2.0

.editorconfig, .prettierrc.json, .travis.yml, CHANGELOG.md, CODE_OF_CONDUCT.md, CONTRIBUTING.md, README.md, examples/react-recorder-volume-indicator/app/components/Button/index.css, jsdoc.json, package.json, packages/player/README.md, packages/recorder/README.md
- Add other files to the pre-commit hook (CSS, Markdown, Yaml)
- Removed not valid config option "editorConfig"
- Added markdown to .editorconfig
- Prettify files in project
- json
- markdown
- yaml
- css
=> Improve prettier support

CHANGELOG.md, packages/api/challenges/pronunciation/analysis.spec.js, packages/api/utils/audio-over-socket.js, packages/api/utils/audio-over-socket.spec.js
=> Improve recorder events

CHANGELOG.md, packages/api/utils/audio-over-socket.js, packages/api/utils/audio-over-socket.spec.js
- Unregister RPC functions before adding a new one
- Remove event listeners before adding them
=> Unregister events and registrations

CHANGELOG.md, packages/api/package.json
=> Prepare release

CHANGELOG.md, packages/recorder/README.md
Update the readme of the recorder to be more accurate.
- Removed some functions that are not here anymore;
- Add the factory functions for the plugins to the API section
=> Update documentation for the recorder

CHANGELOG.md, packages/api/package.json, packages/recorder/package.json
Updating changelog and version numbers etc.
=> Perpare release 5.2.0

CHANGELOG.md, packages/api/utils/audio-over-socket.js
- Reset the `lastChunk` variable after it was used;
- Make sure to only try to unregister when there is actually a known registration;
Closes #358 
Closes #376
=> Improve audio streaming utils

CHANGELOG.md, packages/api/communication/websocket.js, packages/api/communication/websocket.spec.js
=> Fix raised TypeError

CHANGELOG.md, packages/api/package.json, packages/player/package.json, packages/recorder/package.json
=> Prepare v5.3.0

CHANGELOG.md, packages/api/challenges/feedback/speech.js, packages/api/challenges/feedback/speech.spec.js
Expose the argument that makes it possible to override the dataavailable event to listen on. This can be particularly convenient when using the BufferPlugin.
=> Make custom data event usable

.travis.yml, CHANGELOG.md
- Remove the secret from the config (add it directly to travis)
- Update config to edge
- Drop nodejs 8 support (for travis)
- Add nodejs 12 support (for travis)
=> Travis updates

CHANGELOG.md, packages/api/challenges/feedback/speech.js, packages/api/challenges/feedback/speech.spec.js
Regardless of failure or success, close the connection.
=> Improve closing websocket connection

CHANGELOG.md, packages/api/index.js, packages/api/package.json
- `api`
- Version number in the main index.js file updated.
- Exposed websocket connection which apparently was hidden.
=> Some fixes
