administrative-sdk/connection/connection-controller.js
audio-recorder.js
test/connectionSpec.js

Add method to remove all event listeners from a recorder when cancelling streaming.

refactor: add alloff event

---

administrative-sdk/choice-recognition/choice-recognition-controller.js
administrative-sdk/pronunciation-analysis/pronunciation-analysis-controller.js
administrative-sdk/speech-recording/speech-recording-controller.js
test/choice-recognitionSpec.js
test/pronunciation-analysisSpec.js
test/speech-recordingSpec.js

Fix recording, recognition and analysis id set to null before being returned to user.

fix(streaming): fix id set to null early

---

administrative-sdk/pronunciation-analysis/pronunciation-analysis-controller.js

Use the .progress method on call promise to send out intermediate
messages instead of .tap which executed on completion of the promise.

refactor(pronunciationanalysis): use progress instead of tap

---

administrative-sdk/connection/connection-controller.js
test/connectionSpec.js

GetAuthHeaders now uses promises which allows the _secureAjax methods to
directly use this method to make a request. It also gives errors through
the promise.reject instead of throwing an error.

refactor(connection): use promise in get auth headers

---

audio-player.js
cordova-media-player.js
test/audio-playerSpec.js
test/cordova-media-playerSpec.js
test/web-audio-playerSpec.js
web-audio-player.js

Add a pause method in addition to the existing stop method. This allows
for people to react to events coming from either an actual pause of the
audio playing, or a stop, which also resets the audio time back to 0.

feat(mediaplayers): add stop and pause functionality

---

test/toolsSpec.js
tools.js

Fix ticking behaviour to update value after using the callback and
to use the callback when resetting the timer.

fix(stopwatch): fix ticking behaviour

---

administrative-sdk/connection/connection-controller.js
test/connectionSpec.js

Remove the intermediate method to _websocketconnect. Previously this
was used so autobahn could be mocked, but with rewireify it is no
longer needed to do it like this.

refactor(connection): use one method to connect

---

administrative-sdk/basic-auth/basic-auth-controller.js
administrative-sdk/connection/connection-controller.js
test/basic-authSpec.js
test/connectionSpec.js

Fix errors being thrown if the server responded with nothing.
The .json method expected a json object but if the server responded
with nothing an error would be thrown. First parse the response to text and see if something exists and then handle it further.

fix(promises): fix promise response

---

administrative-sdk/connection/connection-controller.js

Auth headers will always be defined, or an error would have been thrown.

refactor(connection): remove header check

---

administrative-sdk/connection/connection-controller.js
test/connectionSpec.js

Use the token to connect from the settings instead of from a parameter.

feat(connection): use token from settings

---

deploy.sh

Don't build docs on PRs or commits to other branches as the environment
variables are not available there.

fix(deploy): dont build docs on prs

---

.travis.yml

The `before_deploy` command referenced a nonexisting file.

fix(travis): fix babel before_deploy command

---

package.json

WhenJs is a runtime dependency, not a development dependency.

chore(package): move when from dev dep

---

deploy.sh
package.json

The deploy script couldn't find esdoc when travis was preparing a release.
`./deploy.sh: line 34: esdoc: command not found`
Was the error travis gave.
I'm open to suggestions on how to make Travis not explode everytime I want to release.

fix(deploy): fix esdoc command

---

.travis.yml

The build of the documentation relies on npm, which requires npm
dependencies to have been installed.
This should fix #165.

chore(travis): skip stash from gh-pages deployment

---

.travis.yml
deploy.sh
package.json

Instead of using the babel script `before_deploy`, use it as npm script in
`deploy.sh`, which only runs it once and sets up the right `build/` directory for
the npm release.

chore(deploy): use babel as npm script

---

src/index.js

Remove the exporting of analyses, recordings and recognition classes.
They are obtained as result from streaming and thus do not need to be
created by the user manually.

fix(index): remove stream result exports

---

.babelrc
test/administrative-sdkSpec.js

Using `2015-loose` mode is deprecated for babel 6+. Use the new method
to use loose mode.

fix(babel): use nondeprecated loose

---

src/administrative-sdk/choice-recognition/choice-recognition-controller.js
src/administrative-sdk/speech-recording/speech-recording-controller.js
test/choice-recognitionSpec.js
test/pronunciation-analysisSpec.js
test/speech-recordingSpec.js

Resolve the streaming with the streaming id separately from the result
object.

refactor(streaming): send streaming id separately

---

src/administrative-sdk/choice-challenge/choice-challenge-controller.js
src/administrative-sdk/choice-recognition/choice-recognition-controller.js
src/administrative-sdk/organisation/organisation-controller.js
src/administrative-sdk/pronunciation-analysis/pronunciation-analysis-controller.js
src/administrative-sdk/pronunciation-challenge/pronunciation-challenge-controller.js
src/administrative-sdk/speech-challenge/speech-challenge-controller.js
src/administrative-sdk/speech-recording/speech-recording-controller.js
src/administrative-sdk/student/student-controller.js

Add the private annotation to controllers so they don't show up in
documentation. All method documentation can be read from the main
facade class.

docs: make controllers private

---

package.json

Copy README.md to the build folder so there is something to read on the
npm page.

chore(package): copy readme to build

---

src/administrative-sdk/administrative-sdk.js
src/administrative-sdk/speech-challenge/speech-challenge-controller.js
src/administrative-sdk/speech-challenge/speech-challenge.js
test/administrative-sdkSpec.js
test/speech-challengeSpec.js
test/speech-recordingSpec.js

When creating a speech challenge, require the audio blob as a separate parameter, since it is not returned by the API (only the download url) and is thus unnecesary in the model.

Audio as separate param

---

src/audio/audio-player.js
src/audio/cordova-media-player.js
src/audio/web-audio-player.js
test/audio-playerSpec.js
test/cordova-media-playerSpec.js
test/web-audio-playerSpec.js

Add methods to set and get the playbackrate for html5 audio.
In cordova these are useless methods. The audio player also binds the
stopwatch and factors the playbackrate into the expected duration
of the audio, as this is not done by the HTML5 audio.
Fixes #221

feat(audioplayer): add playbackrate manipulation

---

src/administrative-sdk/utils/base64-utils.js
src/audio/cordova-media-player.js
src/audio/cordova-media-recorder.js
src/audio/media-recorder.js
src/audio/web-audio-player.js
src/audio/web-audio-recorder.js

Set some classes to private to avoid them showing up in the docs.
The user does not need to know about these internal classes.

docs: remove some classes from docs

---

src/administrative-sdk/pronunciation-challenge/pronunciation-challenge-controller.js
src/administrative-sdk/pronunciation-challenge/pronunciation-challenge.js
test/pronunciation-analysisSpec.js
test/pronunciation-challengeSpec.js

Deploy audio as a separate parameter when creating a pronunciationChallenge.
The audio file is not returned by the API, only the download url, so enter
the download url as parameter to the challenge constructor.

feat(pronunciationchallenge): audio url as separate parameter

---

src/audio/audio-player.js
src/audio/cordova-media-player.js
src/audio/web-audio-player.js
test/audio-playerSpec.js
test/cordova-media-playerSpec.js
test/web-audio-playerSpec.js

Add methods for volume control. Set muted, togglemute, set and get audio
volume and get muted state. Volume level cannot be gotten from the cordova
media as that is not implemented by the Cordova Media class.
Fixes #238

feat(audioplayers): volume control

---

src/audio/web-audio-player.js

Switch logging statement to after the audio starts playing so it logs the correct time.
Fixes #241

fix(webaudioplayer): log correct playing time

---

package.json
src/audio/audio-recorder.js
test/audio-recorderSpec.js

node-uuid has been deprecated in favor of uuid.

refactor: replace node-uuid with uuid

---

.eslintignore

ESLint was also used to check generated JavaScript files, which don't
follow the style guide.

chore: add .eslintignore

---

src/administrative-sdk/pronunciation-analysis/pronunciation-analysis-controller.js

A promise in startStreamingPronunciationAnalysis was called, but not
awaited. This caused a race condition.
This was discovered and fixed by flattening the promise chain.

fix(pronunciation-analysis): fix a race condition

---

src/audio/audio-recorder.js

When a record timeout is triggered, the stop function of a recorder
is usually called in the timer tick handler. Sometimes, a new tick
might be triggered sooner than the recorder is stopped. Not a
problem, so don't raise concerns.

fix(audio-recorder): don't raise concerns on stopped recorder

---

src/administrative-sdk/connection/connection-controller.js
test/connectionSpec.js

Prevent `getOauth2Token` from doing more than its name suggests. Instead
of generating a scope, accept a scope. When no scope is available, don't
set the `scopes` param.

refactor(Connection): generate scope in `getUserAuth`

---

src/audio/audio-tools.js
test/audio-toolsSpec.js

The animation loop somehow could not break out of its loop when
needed. By taking another approach to access the value for allowing
the loop ('willAnimate') things got better.
Besides setting the analyzer to stop also a resume function has been
added to be able to reuse the VolumeMeter component.

fix(VolumeMeter): be able to break the analyzing loop

---

src/administrative-sdk/progress/progress-controller.js
test/progressSpec.js

Support providing a groupId to the progress controller. This way the
number of results for progress can be limited to users in a specific
group. Use case: a teacher wants to see progress of students in his
group.

feat(Progress): add groupId as param for getting progress

---

src/administrative-sdk/administrative-sdk.js
test/administrative-sdkSpec.js

`ProgressController.getProgress` allows for an optional `groupId`
parameter. Also expose this through the `AdministrativeSdk` so it can be
actually used.

fix(progress): allow to fetch progress for a group

---

src/api/auth.js
src/api/auth.spec.js

The response body is currently used to also store the token for later usage (i.e. store in localStorage) Also `/token` should have been `/tokens`.
Closes: #289
Fixes: #288

fix: make the correct token request

---

README.md

Display the build result like any true open-source project does to be
more transparent about the project status.

chore: proudly display the travis results

---

CHANGELOG.md
src/audio/audio-recorder.js
test/audio-recorderSpec.js

Add delay to actually start recording. This is in favor of using the backend his/her trim feature.
Closes #311 
Fixes #312

Add delay to recorder

---

CHANGELOG.md
src/api/utils/audio-over-socket.js

As required by API docs, when we pause the recorder we must also resend the WAVE header on resume.

Resend header after pause

---

CHANGELOG.md
packages/api/CHANGELOG.md
packages/api/communication/index.js

There was an error in the request for posting to an URL with FormData.
By "forcing" the `Content-Type: multipart/form-data` header we omitted
the needed boundary information. The browser and/or some NodeJS process
will set this automatically when you try to post FormData: so there is
no need to specify it here this way.
Once merged a new version can be made (v4.0.1 for API).

Fix content type header

---

packages/api/CHANGELOG.md
packages/api/challenges/choice/recognition.js
packages/api/challenges/choice/recognition.spec.js
packages/api/package.json

Streaming only works on our "older" backend. Since v4 this changed to streaming. We do have a couple of situations where we need the old streaming variant thus this is added in this PR.
This PR also prepares the v4.0.1 tag release for this.

Add non-streaming recognise option

---

CHANGELOG.md
karma.conf.js
packages/api/package.json
packages/api/utils/audio-over-socket.js

Allow multiple writes for speech recordings by using the `timeslice` feature of the recorder.
This is done the same way as we do it for streaming audio.
Fixes #348

Fix recording sending chunks

---

CHANGELOG.md
packages/recorder/index.js
packages/recorder/package.json

The `recorder.getAudioSpecs()` was returning some hard-coded values that where not true on some devices. If the recorded and processed audio sounded like it was speedup: this was why.

Fix recorder get settings

---

CHANGELOG.md
README.md
package.json
packages/api/README.md
packages/api/package.json
packages/player/README.md
packages/player/package.json
packages/recorder/package.json

Prepare the new version to be tagged.
Also one minor fix: set core-js as peer dependency.

Prepare v5 release

---

packages/recorder/index.js
packages/recorder/index.spec.js
packages/recorder/plugins/buffer/buffer.js
packages/recorder/plugins/buffer/index.js
packages/recorder/plugins/buffer/index.spec.js

Example code will be in the next PR.
This introduces the BufferPlugin. Enable it on the recorder to be able to lookback.
Use `secondsToBuffer` to set the length to buffer. Use `requestBufferedData()` to trigger getting the data, and optionally pass the number of seconds you want to that function. Finally, add an `bufferdataavailable` listener to the recorder to get the buffered data.

Feat recorder plugin buffer

---

packages/recorder/plugins/buffer/index.js
packages/recorder/plugins/buffer/index.spec.js

In stead of dispatching an `bufferdataavailable` event, allow overriding te event.
This could be convenient to use the `dataavailable` event, which is needed to use for the Feedback API.

Make it possible to override the event

---

CHANGELOG.md
packages/api/communication/websocket.spec.js
packages/api/utils/audio-over-socket.spec.js

It seems the async/await way of doing the test causes them to sometimes
fail because some other test messes up. Messes up is due to using some
variables that get overridden multiple times making them unreliable.
Moved this to a more solid approach and put it all in a setup function.
This should make the tets more reliable and less prone to "randomly" fail.

Refactor some async tests

---

CHANGELOG.md
packages/api/progress/index.js
packages/api/progress/index.spec.js

Fix the unclear message "groups.forEach is not a function" by allowing both an array and string as input for the Progress.getById api. If an invalid value is passed it will be ignored.
This also allows to getById by just passing a role and no group more conveniently.
Fix #365 
Close #368

Fix passing group id as string

---

CHANGELOG.md
packages/api/challenges/feedback/speech.js
packages/api/package.json

Close the websocket connection after usage with the Feedback API.

Improve connection handling

---

CHANGELOG.md
packages/api/communication/websocket.js
packages/api/utils/audio-over-socket.js
packages/api/utils/audio-over-socket.spec.js
packages/api/utils/index.js
packages/api/utils/index.spec.js

- Make it possible to resolve the autobahn deferred when stopping the recorder when no audio was sent;
- Added a cheap test that tries to look at the blob that is send to the backend. In some cases it will not be tried to send;
- Don't assume a reconnect;
Fixes #386

Improve audio stream for feedback API

---

CHANGELOG.md
packages/recorder/index.js
packages/recorder/package.json

Add constraints to the call of `createMediaStream`. This way we can be sure a recording session will be done with the minimum recording quality (sampleRate) that the ITSLanguage backend needs to perform analysis on.
fixes #391

Use mediadevice constraints

---

CHANGELOG.md
packages/api/communication/websocket.js
packages/api/communication/websocket.spec.js
packages/api/package.json

- Do not remove the onclose handler
- use the reason when the connection is closed
- prepare new patch version (v5.6.1)
Fixes #397

fix: do not remove the onclose handler
